vich_uploader:
    db_driver: orm

    mappings:
       question_images:
           uri_prefix: /question_images
           upload_destination: '%kernel.project_dir%/public/question_images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
