version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:@db:3306/Myquiz?serverVersion=5.7&charset=utf8mb4"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: Myquiz
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_data:/var/lib/mysql
      - ./myquiz.sql:/docker-entrypoint-initdb.d/myquiz.sql
volumes:
  mysql_data:
